<<<<<<< HEAD
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const ACCOUNTS_KEY = "daymark.accounts.v2";
const SESSION_KEY = "daymark.session.v2";
const today = new Date(); today.setHours(0, 0, 0, 0);
const keyOf = (date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const todayKey = keyOf(today);
let accounts = readAccounts(), user = null, authMode = "login";
let month = new Date(today.getFullYear(), today.getMonth(), 1), selectedDate = todayKey;
let timer = null, timerMode = "work", timerSeconds = 25 * 60, workMinutes = 25, breakMinutes = 5, notified = new Set();
let toastTimeout;

function readAccounts(){try{return JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||"{}")}catch{return {}}}
function save(){localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(accounts))}
function initializeUser(account){account.data ||= {};const d=account.data;d.tasks ||= {};d.focus ||= {};d.settings ||= {name:account.username,theme:"light",work:25,rest:5};d.points ||= 0;d.bestStreak ||= 0;}
function data(){return user.data}
function esc(text){return String(text).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function taskListFor(date=todayKey){data().tasks[date] ||= [];return data().tasks[date]}
function persist(){save()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove("show"),2200)}

function setAuthMode(mode){authMode=mode;const register=mode==="register";$("#authTitle").textContent=register?"Create your space.":"Welcome back.";$("#authSubtitle").textContent=register?"Make an account to start planning.":"Sign in to continue with your day.";$("#authSubmit").textContent=register?"Create account":"Sign in";$("#authSwitchText").textContent=register?"Already have an account?":"New to Daymark?";$("#authSwitch").textContent=register?"Sign in":"Create an account";$("#authPassword").autocomplete=register?"new-password":"current-password";$("#authError").textContent=""}
$("#authSwitch").onclick=()=>setAuthMode(authMode==="login"?"register":"login");
$("#authForm").onsubmit=(event)=>{event.preventDefault();const username=$("#authUsername").value.trim().toLowerCase(),password=$("#authPassword").value;$("#authError").textContent="";if(authMode==="register"){if(accounts[username]){$("#authError").textContent="That username is already taken.";return}accounts[username]={username,password,data:{}};initializeUser(accounts[username]);save()}else if(!accounts[username]||accounts[username].password!==password){$("#authError").textContent="Username or password is incorrect.";return}localStorage.setItem(SESSION_KEY,username);openApp(username)};
function openApp(username){user=accounts[username];if(!user)return;initializeUser(user);$("#authScreen").classList.add("hidden");$("#app").classList.remove("hidden");const s=data().settings;workMinutes=Number(s.work)||25;breakMinutes=Number(s.rest)||5;$("#workMinutes").value=workMinutes;$("#breakMinutes").value=breakMinutes;$("#displayName").value=s.name||username;$("#accountName").textContent=s.name||username;$("#avatar").textContent=(s.name||username)[0].toUpperCase();$("#accountDetails").textContent=`Signed in as ${username}`;$("#themeSelect").value=s.theme||"light";applyTheme();const h=new Date().getHours();$("#welcomeHeading").innerHTML=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"}, ${esc(s.name||username)}<span class="accent">.</span>`;$("#todayHeading").textContent=today.toLocaleDateString("en",{weekday:"long",month:"long",day:"numeric"});$("#datePill").textContent=today.toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"});renderAll();checkReminders()}
function logout(){localStorage.removeItem(SESSION_KEY);user=null;clearInterval(timer);timer=null;$("#app").classList.add("hidden");$("#authScreen").classList.remove("hidden");$("#authForm").reset();setAuthMode("login")}
$("#logoutButton").onclick=logout;$("#settingsLogout").onclick=logout;

function goto(page){$$(".page").forEach(el=>el.classList.toggle("active",el.id===`page-${page}`));$$(".nav-link").forEach(el=>el.classList.toggle("active",el.dataset.page===page));$("#breadcrumb").textContent=`Workspace / ${({home:"Home",week:"Weekly tasks",calendar:"Calendar",focus:"Pomodoro",history:"History",settings:"Settings"})[page]}`;if(page==="calendar")renderCalendar();if(page==="week")renderWeek()}
$$('.nav-link').forEach(button=>button.onclick=()=>goto(button.dataset.page));$$('[data-goto]').forEach(button=>button.onclick=()=>goto(button.dataset.goto));

function weekDates(){const start=new Date(today);start.setDate(today.getDate()-today.getDay());return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function addTask(date=todayKey){const title=prompt("What task do you want to add?");if(!title||!title.trim())return;let deadline=prompt("Optional deadline time (for example 17:30). Leave blank for no reminder:")||"";if(deadline&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(deadline)){toast("Use 24-hour time such as 17:30; task added without a reminder.");deadline=""}taskListFor(date).push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,title:title.trim(),done:false,deadline,pointsAwarded:false});persist();renderAll();toast("Task added to your plan")}
$("#addToday").onclick=()=>addTask(todayKey);$("#addWeekTask").onclick=()=>{const options=weekDates().map(d=>`${d.toLocaleDateString("en",{weekday:"long"})} (${keyOf(d)})`).join("\n");const choice=prompt(`Choose the day by entering its date (YYYY-MM-DD):\n${options}`,todayKey);if(choice&&weekDates().some(d=>keyOf(d)===choice))addTask(choice);else if(choice)toast("Choose a date in this week")};$("#addCalendarTask").onclick=$("#addSelectedDate").onclick=()=>addTask(selectedDate);

function allTasks(){return Object.entries(data().tasks).flatMap(([date,tasks])=>tasks.map(task=>({...task,date})))}
function completedOn(date){return (data().tasks[date]||[]).filter(t=>t.done).length}
function setTaskState(task,date,done){task.done=done;if(done){task.completedAt=date;if(!task.pointsAwarded){data().points+=10;task.pointsAwarded=true}}else{task.completedAt=null}persist();renderAll()}
function makeTaskRow(task,date){const row=document.createElement("div");row.className=`task-row${task.done?" done":""}`;const deadline=task.deadline?`<span class="task-meta">⏰ ${esc(task.deadline)}</span>`:"";row.innerHTML=`<input class="task-check" type="checkbox" ${task.done?"checked":""} aria-label="Mark task complete"><span class="task-name">${esc(task.title)}</span>${deadline}<button class="icon-button delete-task" aria-label="Delete task" title="Delete task">×</button>`;row.querySelector("input").onchange=e=>setTaskState(task,date,e.target.checked);row.querySelector(".delete-task").onclick=()=>{const list=data().tasks[date];list.splice(list.indexOf(task),1);persist();renderAll()};return row}
function renderToday(){const tasks=taskListFor(),list=$("#todayList");list.innerHTML="";if(!tasks.length)list.innerHTML='<div class="empty">Nothing on your list yet. Add a task to get started.</div>';tasks.forEach(task=>list.append(makeTaskRow(task,todayKey)));const done=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(done/tasks.length*100):0;$("#todayCount").textContent=`${done} / ${tasks.length}`;$("#todayPercent").textContent=tasks.length?`${rate}% complete today`:"Start with one small step";$("#dailyProgressText").textContent=`${rate}%`;
  $("#dailyProgress").style.width=`${rate}%`;const last7=weekDates(),focus=last7.reduce((sum,d)=>sum+(data().focus[keyOf(d)]||0),0);$("#focusCount").textContent=`${focus} min`;$("#pointsCount").textContent=data().points;const streak=calculateStreak();data().bestStreak=Math.max(data().bestStreak||0,streak);$("#streakCount").textContent=`${streak} ${streak===1?"day":"days"}`;$("#bestStreak").textContent=`Best: ${data().bestStreak} ${data().bestStreak===1?"day":"days"}`;persist();renderHomeChart();renderReminders()}
$("#clearDone").onclick=()=>{data().tasks[todayKey]=taskListFor().filter(t=>!t.done);persist();renderAll();toast("Completed tasks cleared")};
function renderHomeChart(){const dates=weekDates(),counts=dates.map(d=>completedOn(keyOf(d))),max=Math.max(3,...counts);$("#homeChart").innerHTML=dates.map((d,i)=>`<div class="chart-column"><small>${counts[i]||""}</small><div class="chart-bar ${keyOf(d)===todayKey?"current":""}" style="height:${Math.max(5,counts[i]/max*78)}%"></div><small>${d.toLocaleDateString("en",{weekday:"short"})}</small></div>`).join("");const done=counts.reduce((a,b)=>a+b,0),planned=dates.reduce((n,d)=>n+(data().tasks[keyOf(d)]||[]).length,0),pct=planned?Math.round(done/planned*100):0;$("#weekSummary").innerHTML=`<span>${done} completed of ${planned}</span><strong>${pct}% this week</strong>`}
function renderWeek(){const dates=weekDates(),grid=$("#weekGrid");grid.innerHTML="";let total=0,done=0,points=0;dates.forEach(date=>{const key=keyOf(date),tasks=data().tasks[key]||[],complete=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(complete/tasks.length*100):0;total+=tasks.length;done+=complete;points+=tasks.filter(t=>t.done&&t.pointsAwarded).length*10;const card=document.createElement("article");card.className=`week-day-card${key===todayKey?" today":""}`;card.innerHTML=`<div class="week-day-head"><h2>${date.toLocaleDateString("en",{weekday:"long"})}</h2><span>${date.toLocaleDateString("en",{month:"short",day:"numeric"})}</span></div><div class="day-analysis"><b>${rate}%</b> complete · ${complete}/${tasks.length} tasks</div><div class="progress-track"><div class="progress-fill" style="width:${rate}%"></div></div><div class="task-list"></div><button class="day-add">＋ Add task</button>`;const taskBox=card.querySelector(".task-list");if(tasks.length)tasks.forEach(t=>taskBox.append(makeTaskRow(t,key)));else taskBox.innerHTML='<div class="empty">No tasks planned</div>';card.querySelector(".day-add").onclick=()=>addTask(key);grid.append(card)});$("#weekDone").textContent=`${done} / ${total}`;$("#weekPercent").textContent=`${total?Math.round(done/total*100):0}%`;$("#weekPoints").textContent=points}

function renderCalendar(){if(!user)return;const year=month.getFullYear(),m=month.getMonth(),first=new Date(year,m,1),count=new Date(year,m+1,0).getDate(),offset=first.getDay(),grid=$("#calendarGrid");$("#monthTitle").textContent=month.toLocaleDateString("en",{month:"long",year:"numeric"});grid.innerHTML=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-label">${d}</div>`).join("");for(let i=0;i<42;i++){const n=i-offset+1,date=new Date(year,m,n),key=keyOf(date),valid=n>0&&n<=count,cell=document.createElement("button");cell.className=`calendar-day${valid?"":" muted-day"}${key===todayKey?" today":""}${key===selectedDate?" selected":""}`;cell.innerHTML=`<span>${date.getDate()}</span>${(data().tasks[key]||[]).slice(0,2).map(t=>`<small class="calendar-event">${esc(t.title)}</small>`).join("")}`;cell.onclick=()=>{selectedDate=key;renderCalendar()};grid.append(cell)}const date=new Date(`${selectedDate}T00:00:00`);$("#selectedDateTitle").textContent=date.toLocaleDateString("en",{weekday:"long",month:"long",day:"numeric"});const agenda=$("#calendarAgenda"),tasks=data().tasks[selectedDate]||[];agenda.innerHTML="";if(!tasks.length)agenda.innerHTML='<div class="empty">No tasks for this date yet.</div>';tasks.forEach(t=>agenda.append(makeTaskRow(t,selectedDate)))}
$("#prevMonth").onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};

function renderReminders(){const now=new Date(),items=allTasks().filter(t=>t.deadline&&!t.done&&new Date(`${t.date}T${t.deadline}:00`)>=new Date(now.getTime()-60*60*1000)).sort((a,b)=>`${a.date}T${a.deadline}`.localeCompare(`${b.date}T${b.deadline}`)).slice(0,6),box=$("#reminderList");box.innerHTML="";if(!items.length){box.innerHTML='<div class="empty">No upcoming deadlines. Add a task with a time to set a reminder.</div>';return}items.forEach(t=>{const row=document.createElement("div");row.className="reminder-row";row.innerHTML=`<span class="reminder-time">${t.date===todayKey?"Today":new Date(`${t.date}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric"})} · ${esc(t.deadline)}</span><span>${esc(t.title)}</span>`;box.append(row)})}
function checkReminders(){if(!user)return;const now=new Date();allTasks().forEach(t=>{if(!t.deadline||t.done)return;const when=new Date(`${t.date}T${t.deadline}:00`),delta=when-now;if(delta>=0&&delta<60000&&!notified.has(t.id)){notified.add(t.id);toast(`Deadline now: ${t.title}`);if("Notification" in window&&Notification.permission==="granted")new Notification("Daymark reminder",{body:t.title})}})}
$("#notifyButton").onclick=async()=>{if(!("Notification" in window)){toast("Browser notifications are not available here");return}const permission=await Notification.requestPermission();toast(permission==="granted"?"Browser reminders enabled":"Browser notification permission not granted")};

function calculateStreak(){const dates=new Set(allTasks().filter(t=>t.done).map(t=>t.completedAt||t.date));let d=new Date(today);if(!dates.has(keyOf(d)))d.setDate(d.getDate()-1);let count=0;while(dates.has(keyOf(d))){count++;d.setDate(d.getDate()-1)}return count}
function renderHistory(){const tasks=allTasks(),completed=tasks.filter(t=>t.done),rate=tasks.length?Math.round(completed.length/tasks.length*100):0,focus=Object.values(data().focus).reduce((sum,n)=>sum+n,0);$("#historyDone").textContent=completed.length;$("#historyRate").textContent=`${rate}%`;$("#historyFocus").textContent=`${focus} min`;$("#historyPoints").textContent=data().points;const chartDates=Array.from({length:14},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-(13-i));return d}),counts=chartDates.map(d=>completed.filter(t=>(t.completedAt||t.date)===keyOf(d)).length),max=Math.max(2,...counts);$("#historyChart").innerHTML=chartDates.map((d,i)=>`<div class="history-bar-wrap"><small>${counts[i]||""}</small><div class="history-bar" title="${counts[i]} completed" style="height:${Math.max(4,counts[i]/max*78)}%"></div><small>${d.getDate()}</small></div>`).join("");const list=$("#historyList");list.innerHTML="";completed.sort((a,b)=>(b.completedAt||b.date).localeCompare(a.completedAt||a.date)).slice(0,30).forEach(t=>{const row=document.createElement("div");row.className="task-row done";row.innerHTML=`<span class="tag">+${t.pointsAwarded?10:0} pts</span><span class="task-name">${esc(t.title)}</span><span class="task-meta">${new Date(`${t.completedAt||t.date}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric"})}</span>`;list.append(row)});if(!completed.length)list.innerHTML='<div class="empty">Finished tasks will show here as you make progress.</div>'}

function renderAll(){renderToday();renderWeek();renderCalendar();renderHistory();renderReminders()}
function applyTheme(){const theme=data().settings.theme||"light";document.body.classList.remove("theme-dark","theme-lavender","theme-ocean","theme-warm");if(theme!=="light")document.body.classList.add(`theme-${theme}`)}
$("#themeSelect").onchange=e=>{data().settings.theme=e.target.value;applyTheme();persist()};$("#displayName").onchange=e=>{const name=e.target.value.trim()||user.username;data().settings.name=name;$("#accountName").textContent=name;$("#avatar").textContent=name[0].toUpperCase();const h=new Date().getHours();$("#welcomeHeading").innerHTML=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"}, ${esc(name)}<span class="accent">.</span>`;persist()};

function applyTimerSettings(){const work=Number($("#workMinutes").value),rest=Number($("#breakMinutes").value);if(!Number.isInteger(work)||work<1||work>180||!Number.isInteger(rest)||rest<1||rest>60){toast("Choose work 1–180 min and break 1–60 min");return}workMinutes=work;breakMinutes=rest;data().settings.work=work;data().settings.rest=rest;timerMode="work";$$('.mode').forEach(b=>b.classList.toggle("active",b.dataset.mode==="work"));resetTimer();persist();toast("Timer lengths updated")}
$("#applyTimerSettings").onclick=applyTimerSettings;function resetTimer(){clearInterval(timer);timer=null;timerSeconds=(timerMode==="work"?workMinutes:breakMinutes)*60;$("#timerStart").textContent="Start";$("#timerStatus").textContent="Ready when you are";showTimer()}
function showTimer(){$("#timerDisplay").textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,"0")}:${String(timerSeconds%60).padStart(2,"0")}`}
$$('.mode').forEach(b=>b.onclick=()=>{timerMode=b.dataset.mode;$$('.mode').forEach(x=>x.classList.toggle("active",x===b));resetTimer()});$("#timerReset").onclick=resetTimer;$("#timerStart").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("#timerStart").textContent="Resume";$("#timerStatus").textContent="Paused";return}$("#timerStart").textContent="Pause";$("#timerStatus").textContent=timerMode==="work"?"You’re in a focus session":"Take a little breather";timer=setInterval(()=>{timerSeconds--;showTimer();if(timerSeconds<=0){clearInterval(timer);timer=null;if(timerMode==="work"){data().focus[todayKey]=(data().focus[todayKey]||0)+workMinutes;persist();renderAll()}$("#timerStatus").textContent=timerMode==="work"?"Session complete. Take a break.":"Break complete. Ready to focus?";$("#timerStart").textContent="Start again";toast(timerMode==="work"?"Focus session complete!":"Break complete!")}},1000)};

function search(query){const box=$("#searchResults"),q=query.trim().toLowerCase();if(!q){box.classList.add("hidden");return}const matches=allTasks().filter(t=>t.title.toLowerCase().includes(q)).slice(0,12);const nav=$$(".nav-link").filter(b=>b.textContent.toLowerCase().includes(q));box.innerHTML="";matches.forEach(t=>{const b=document.createElement("button");b.className="search-hit";b.textContent=`${t.title} · ${t.date}${t.done?" · completed":""}`;b.onclick=()=>{selectedDate=t.date;month=new Date(`${t.date}T00:00:00`);goto("calendar");box.classList.add("hidden");$("#globalSearch").value=""};box.append(b)});nav.forEach(n=>{const b=document.createElement("button");b.className="search-hit";b.textContent=`Open ${n.textContent.trim()}`;b.onclick=()=>{goto(n.dataset.page);box.classList.add("hidden")};box.append(b)});if(!matches.length&&!nav.length)box.innerHTML='<div class="empty">No tasks or sections found.</div>';box.classList.remove("hidden")}
$("#globalSearch").oninput=e=>search(e.target.value);$("#globalSearch").onkeydown=e=>{if(e.key==="Escape"){$("#searchResults").classList.add("hidden");e.target.value=""}if(e.key==="Enter"){const first=$("#searchResults .search-hit");if(first)first.click()}};document.addEventListener("click",e=>{if(!e.target.closest(".search-box")&&!e.target.closest(".search-results"))$("#searchResults").classList.add("hidden")});

const storedSession=localStorage.getItem(SESSION_KEY);if(storedSession&&accounts[storedSession])openApp(storedSession);else setAuthMode("login");setInterval(checkReminders,30000);setInterval(()=>{if(user)renderReminders()},60000);
=======
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const ACCOUNTS_KEY = "daymark.accounts.v2";
const SESSION_KEY = "daymark.session.v2";
const today = new Date(); today.setHours(0, 0, 0, 0);
const keyOf = (date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const todayKey = keyOf(today);
let accounts = readAccounts(), user = null, authMode = "login";
let month = new Date(today.getFullYear(), today.getMonth(), 1), selectedDate = todayKey;
let timer = null, timerMode = "work", timerSeconds = 25 * 60, workMinutes = 25, breakMinutes = 5, notified = new Set();
let toastTimeout;

function readAccounts(){try{return JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||"{}")}catch{return {}}}
function save(){localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(accounts))}
function initializeUser(account){account.data ||= {};const d=account.data;d.tasks ||= {};d.focus ||= {};d.settings ||= {name:account.username,theme:"light",work:25,rest:5};d.points ||= 0;d.bestStreak ||= 0;}
function data(){return user.data}
function esc(text){return String(text).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function taskListFor(date=todayKey){data().tasks[date] ||= [];return data().tasks[date]}
function persist(){save()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove("show"),2200)}

function setAuthMode(mode){authMode=mode;const register=mode==="register";$("#authTitle").textContent=register?"Create your space.":"Welcome back.";$("#authSubtitle").textContent=register?"Make an account to start planning.":"Sign in to continue with your day.";$("#authSubmit").textContent=register?"Create account":"Sign in";$("#authSwitchText").textContent=register?"Already have an account?":"New to Daymark?";$("#authSwitch").textContent=register?"Sign in":"Create an account";$("#authPassword").autocomplete=register?"new-password":"current-password";$("#authError").textContent=""}
$("#authSwitch").onclick=()=>setAuthMode(authMode==="login"?"register":"login");
$("#authForm").onsubmit=(event)=>{event.preventDefault();const username=$("#authUsername").value.trim().toLowerCase(),password=$("#authPassword").value;$("#authError").textContent="";if(authMode==="register"){if(accounts[username]){$("#authError").textContent="That username is already taken.";return}accounts[username]={username,password,data:{}};initializeUser(accounts[username]);save()}else if(!accounts[username]||accounts[username].password!==password){$("#authError").textContent="Username or password is incorrect.";return}localStorage.setItem(SESSION_KEY,username);openApp(username)};
function openApp(username){user=accounts[username];if(!user)return;initializeUser(user);$("#authScreen").classList.add("hidden");$("#app").classList.remove("hidden");const s=data().settings;workMinutes=Number(s.work)||25;breakMinutes=Number(s.rest)||5;$("#workMinutes").value=workMinutes;$("#breakMinutes").value=breakMinutes;$("#displayName").value=s.name||username;$("#accountName").textContent=s.name||username;$("#avatar").textContent=(s.name||username)[0].toUpperCase();$("#accountDetails").textContent=`Signed in as ${username}`;$("#themeSelect").value=s.theme||"light";applyTheme();const h=new Date().getHours();$("#welcomeHeading").innerHTML=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"}, ${esc(s.name||username)}<span class="accent">.</span>`;$("#todayHeading").textContent=today.toLocaleDateString("en",{weekday:"long",month:"long",day:"numeric"});$("#datePill").textContent=today.toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"});renderAll();checkReminders()}
function logout(){localStorage.removeItem(SESSION_KEY);user=null;clearInterval(timer);timer=null;$("#app").classList.add("hidden");$("#authScreen").classList.remove("hidden");$("#authForm").reset();setAuthMode("login")}
$("#logoutButton").onclick=logout;$("#settingsLogout").onclick=logout;

function goto(page){$$(".page").forEach(el=>el.classList.toggle("active",el.id===`page-${page}`));$$(".nav-link").forEach(el=>el.classList.toggle("active",el.dataset.page===page));$("#breadcrumb").textContent=`Workspace / ${({home:"Home",week:"Weekly tasks",calendar:"Calendar",focus:"Pomodoro",history:"History",settings:"Settings"})[page]}`;if(page==="calendar")renderCalendar();if(page==="week")renderWeek()}
$$('.nav-link').forEach(button=>button.onclick=()=>goto(button.dataset.page));$$('[data-goto]').forEach(button=>button.onclick=()=>goto(button.dataset.goto));

function weekDates(){const start=new Date(today);start.setDate(today.getDate()-today.getDay());return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function addTask(date=todayKey){const title=prompt("What task do you want to add?");if(!title||!title.trim())return;let deadline=prompt("Optional deadline time (for example 17:30). Leave blank for no reminder:")||"";if(deadline&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(deadline)){toast("Use 24-hour time such as 17:30; task added without a reminder.");deadline=""}taskListFor(date).push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,title:title.trim(),done:false,deadline,pointsAwarded:false});persist();renderAll();toast("Task added to your plan")}
$("#addToday").onclick=()=>addTask(todayKey);$("#addWeekTask").onclick=()=>{const options=weekDates().map(d=>`${d.toLocaleDateString("en",{weekday:"long"})} (${keyOf(d)})`).join("\n");const choice=prompt(`Choose the day by entering its date (YYYY-MM-DD):\n${options}`,todayKey);if(choice&&weekDates().some(d=>keyOf(d)===choice))addTask(choice);else if(choice)toast("Choose a date in this week")};$("#addCalendarTask").onclick=$("#addSelectedDate").onclick=()=>addTask(selectedDate);

function allTasks(){return Object.entries(data().tasks).flatMap(([date,tasks])=>tasks.map(task=>({...task,date})))}
function completedOn(date){return (data().tasks[date]||[]).filter(t=>t.done).length}
function setTaskState(task,date,done){task.done=done;if(done){task.completedAt=date;if(!task.pointsAwarded){data().points+=10;task.pointsAwarded=true}}else{task.completedAt=null}persist();renderAll()}
function makeTaskRow(task,date){const row=document.createElement("div");row.className=`task-row${task.done?" done":""}`;const deadline=task.deadline?`<span class="task-meta">⏰ ${esc(task.deadline)}</span>`:"";row.innerHTML=`<input class="task-check" type="checkbox" ${task.done?"checked":""} aria-label="Mark task complete"><span class="task-name">${esc(task.title)}</span>${deadline}<button class="icon-button delete-task" aria-label="Delete task" title="Delete task">×</button>`;row.querySelector("input").onchange=e=>setTaskState(task,date,e.target.checked);row.querySelector(".delete-task").onclick=()=>{const list=data().tasks[date];list.splice(list.indexOf(task),1);persist();renderAll()};return row}
function renderToday(){const tasks=taskListFor(),list=$("#todayList");list.innerHTML="";if(!tasks.length)list.innerHTML='<div class="empty">Nothing on your list yet. Add a task to get started.</div>';tasks.forEach(task=>list.append(makeTaskRow(task,todayKey)));const done=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(done/tasks.length*100):0;$("#todayCount").textContent=`${done} / ${tasks.length}`;$("#todayPercent").textContent=tasks.length?`${rate}% complete today`:"Start with one small step";$("#dailyProgressText").textContent=`${rate}%`;
  $("#dailyProgress").style.width=`${rate}%`;const last7=weekDates(),focus=last7.reduce((sum,d)=>sum+(data().focus[keyOf(d)]||0),0);$("#focusCount").textContent=`${focus} min`;$("#pointsCount").textContent=data().points;const streak=calculateStreak();data().bestStreak=Math.max(data().bestStreak||0,streak);$("#streakCount").textContent=`${streak} ${streak===1?"day":"days"}`;$("#bestStreak").textContent=`Best: ${data().bestStreak} ${data().bestStreak===1?"day":"days"}`;persist();renderHomeChart();renderReminders()}
$("#clearDone").onclick=()=>{data().tasks[todayKey]=taskListFor().filter(t=>!t.done);persist();renderAll();toast("Completed tasks cleared")};
function renderHomeChart(){const dates=weekDates(),counts=dates.map(d=>completedOn(keyOf(d))),max=Math.max(3,...counts);$("#homeChart").innerHTML=dates.map((d,i)=>`<div class="chart-column"><small>${counts[i]||""}</small><div class="chart-bar ${keyOf(d)===todayKey?"current":""}" style="height:${Math.max(5,counts[i]/max*78)}%"></div><small>${d.toLocaleDateString("en",{weekday:"short"})}</small></div>`).join("");const done=counts.reduce((a,b)=>a+b,0),planned=dates.reduce((n,d)=>n+(data().tasks[keyOf(d)]||[]).length,0),pct=planned?Math.round(done/planned*100):0;$("#weekSummary").innerHTML=`<span>${done} completed of ${planned}</span><strong>${pct}% this week</strong>`}
function renderWeek(){const dates=weekDates(),grid=$("#weekGrid");grid.innerHTML="";let total=0,done=0,points=0;dates.forEach(date=>{const key=keyOf(date),tasks=data().tasks[key]||[],complete=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(complete/tasks.length*100):0;total+=tasks.length;done+=complete;points+=tasks.filter(t=>t.done&&t.pointsAwarded).length*10;const card=document.createElement("article");card.className=`week-day-card${key===todayKey?" today":""}`;card.innerHTML=`<div class="week-day-head"><h2>${date.toLocaleDateString("en",{weekday:"long"})}</h2><span>${date.toLocaleDateString("en",{month:"short",day:"numeric"})}</span></div><div class="day-analysis"><b>${rate}%</b> complete · ${complete}/${tasks.length} tasks</div><div class="progress-track"><div class="progress-fill" style="width:${rate}%"></div></div><div class="task-list"></div><button class="day-add">＋ Add task</button>`;const taskBox=card.querySelector(".task-list");if(tasks.length)tasks.forEach(t=>taskBox.append(makeTaskRow(t,key)));else taskBox.innerHTML='<div class="empty">No tasks planned</div>';card.querySelector(".day-add").onclick=()=>addTask(key);grid.append(card)});$("#weekDone").textContent=`${done} / ${total}`;$("#weekPercent").textContent=`${total?Math.round(done/total*100):0}%`;$("#weekPoints").textContent=points}

function renderCalendar(){if(!user)return;const year=month.getFullYear(),m=month.getMonth(),first=new Date(year,m,1),count=new Date(year,m+1,0).getDate(),offset=first.getDay(),grid=$("#calendarGrid");$("#monthTitle").textContent=month.toLocaleDateString("en",{month:"long",year:"numeric"});grid.innerHTML=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-label">${d}</div>`).join("");for(let i=0;i<42;i++){const n=i-offset+1,date=new Date(year,m,n),key=keyOf(date),valid=n>0&&n<=count,cell=document.createElement("button");cell.className=`calendar-day${valid?"":" muted-day"}${key===todayKey?" today":""}${key===selectedDate?" selected":""}`;cell.innerHTML=`<span>${date.getDate()}</span>${(data().tasks[key]||[]).slice(0,2).map(t=>`<small class="calendar-event">${esc(t.title)}</small>`).join("")}`;cell.onclick=()=>{selectedDate=key;renderCalendar()};grid.append(cell)}const date=new Date(`${selectedDate}T00:00:00`);$("#selectedDateTitle").textContent=date.toLocaleDateString("en",{weekday:"long",month:"long",day:"numeric"});const agenda=$("#calendarAgenda"),tasks=data().tasks[selectedDate]||[];agenda.innerHTML="";if(!tasks.length)agenda.innerHTML='<div class="empty">No tasks for this date yet.</div>';tasks.forEach(t=>agenda.append(makeTaskRow(t,selectedDate)))}
$("#prevMonth").onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};

function renderReminders(){const now=new Date(),items=allTasks().filter(t=>t.deadline&&!t.done&&new Date(`${t.date}T${t.deadline}:00`)>=new Date(now.getTime()-60*60*1000)).sort((a,b)=>`${a.date}T${a.deadline}`.localeCompare(`${b.date}T${b.deadline}`)).slice(0,6),box=$("#reminderList");box.innerHTML="";if(!items.length){box.innerHTML='<div class="empty">No upcoming deadlines. Add a task with a time to set a reminder.</div>';return}items.forEach(t=>{const row=document.createElement("div");row.className="reminder-row";row.innerHTML=`<span class="reminder-time">${t.date===todayKey?"Today":new Date(`${t.date}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric"})} · ${esc(t.deadline)}</span><span>${esc(t.title)}</span>`;box.append(row)})}
function checkReminders(){if(!user)return;const now=new Date();allTasks().forEach(t=>{if(!t.deadline||t.done)return;const when=new Date(`${t.date}T${t.deadline}:00`),delta=when-now;if(delta>=0&&delta<60000&&!notified.has(t.id)){notified.add(t.id);toast(`Deadline now: ${t.title}`);if("Notification" in window&&Notification.permission==="granted")new Notification("Daymark reminder",{body:t.title})}})}
$("#notifyButton").onclick=async()=>{if(!("Notification" in window)){toast("Browser notifications are not available here");return}const permission=await Notification.requestPermission();toast(permission==="granted"?"Browser reminders enabled":"Browser notification permission not granted")};

function calculateStreak(){const dates=new Set(allTasks().filter(t=>t.done).map(t=>t.completedAt||t.date));let d=new Date(today);if(!dates.has(keyOf(d)))d.setDate(d.getDate()-1);let count=0;while(dates.has(keyOf(d))){count++;d.setDate(d.getDate()-1)}return count}
function renderHistory(){const tasks=allTasks(),completed=tasks.filter(t=>t.done),rate=tasks.length?Math.round(completed.length/tasks.length*100):0,focus=Object.values(data().focus).reduce((sum,n)=>sum+n,0);$("#historyDone").textContent=completed.length;$("#historyRate").textContent=`${rate}%`;$("#historyFocus").textContent=`${focus} min`;$("#historyPoints").textContent=data().points;const chartDates=Array.from({length:14},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-(13-i));return d}),counts=chartDates.map(d=>completed.filter(t=>(t.completedAt||t.date)===keyOf(d)).length),max=Math.max(2,...counts);$("#historyChart").innerHTML=chartDates.map((d,i)=>`<div class="history-bar-wrap"><small>${counts[i]||""}</small><div class="history-bar" title="${counts[i]} completed" style="height:${Math.max(4,counts[i]/max*78)}%"></div><small>${d.getDate()}</small></div>`).join("");const list=$("#historyList");list.innerHTML="";completed.sort((a,b)=>(b.completedAt||b.date).localeCompare(a.completedAt||a.date)).slice(0,30).forEach(t=>{const row=document.createElement("div");row.className="task-row done";row.innerHTML=`<span class="tag">+${t.pointsAwarded?10:0} pts</span><span class="task-name">${esc(t.title)}</span><span class="task-meta">${new Date(`${t.completedAt||t.date}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric"})}</span>`;list.append(row)});if(!completed.length)list.innerHTML='<div class="empty">Finished tasks will show here as you make progress.</div>'}

function renderAll(){renderToday();renderWeek();renderCalendar();renderHistory();renderReminders()}
function applyTheme(){const theme=data().settings.theme||"light";document.body.classList.remove("theme-dark","theme-lavender","theme-ocean","theme-warm");if(theme!=="light")document.body.classList.add(`theme-${theme}`)}
$("#themeSelect").onchange=e=>{data().settings.theme=e.target.value;applyTheme();persist()};$("#displayName").onchange=e=>{const name=e.target.value.trim()||user.username;data().settings.name=name;$("#accountName").textContent=name;$("#avatar").textContent=name[0].toUpperCase();const h=new Date().getHours();$("#welcomeHeading").innerHTML=`${h<12?"Good morning":h<18?"Good afternoon":"Good evening"}, ${esc(name)}<span class="accent">.</span>`;persist()};

function applyTimerSettings(){const work=Number($("#workMinutes").value),rest=Number($("#breakMinutes").value);if(!Number.isInteger(work)||work<1||work>180||!Number.isInteger(rest)||rest<1||rest>60){toast("Choose work 1–180 min and break 1–60 min");return}workMinutes=work;breakMinutes=rest;data().settings.work=work;data().settings.rest=rest;timerMode="work";$$('.mode').forEach(b=>b.classList.toggle("active",b.dataset.mode==="work"));resetTimer();persist();toast("Timer lengths updated")}
$("#applyTimerSettings").onclick=applyTimerSettings;function resetTimer(){clearInterval(timer);timer=null;timerSeconds=(timerMode==="work"?workMinutes:breakMinutes)*60;$("#timerStart").textContent="Start";$("#timerStatus").textContent="Ready when you are";showTimer()}
function showTimer(){$("#timerDisplay").textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,"0")}:${String(timerSeconds%60).padStart(2,"0")}`}
$$('.mode').forEach(b=>b.onclick=()=>{timerMode=b.dataset.mode;$$('.mode').forEach(x=>x.classList.toggle("active",x===b));resetTimer()});$("#timerReset").onclick=resetTimer;$("#timerStart").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("#timerStart").textContent="Resume";$("#timerStatus").textContent="Paused";return}$("#timerStart").textContent="Pause";$("#timerStatus").textContent=timerMode==="work"?"You’re in a focus session":"Take a little breather";timer=setInterval(()=>{timerSeconds--;showTimer();if(timerSeconds<=0){clearInterval(timer);timer=null;if(timerMode==="work"){data().focus[todayKey]=(data().focus[todayKey]||0)+workMinutes;persist();renderAll()}$("#timerStatus").textContent=timerMode==="work"?"Session complete. Take a break.":"Break complete. Ready to focus?";$("#timerStart").textContent="Start again";toast(timerMode==="work"?"Focus session complete!":"Break complete!")}},1000)};

function search(query){const box=$("#searchResults"),q=query.trim().toLowerCase();if(!q){box.classList.add("hidden");return}const matches=allTasks().filter(t=>t.title.toLowerCase().includes(q)).slice(0,12);const nav=$$(".nav-link").filter(b=>b.textContent.toLowerCase().includes(q));box.innerHTML="";matches.forEach(t=>{const b=document.createElement("button");b.className="search-hit";b.textContent=`${t.title} · ${t.date}${t.done?" · completed":""}`;b.onclick=()=>{selectedDate=t.date;month=new Date(`${t.date}T00:00:00`);goto("calendar");box.classList.add("hidden");$("#globalSearch").value=""};box.append(b)});nav.forEach(n=>{const b=document.createElement("button");b.className="search-hit";b.textContent=`Open ${n.textContent.trim()}`;b.onclick=()=>{goto(n.dataset.page);box.classList.add("hidden")};box.append(b)});if(!matches.length&&!nav.length)box.innerHTML='<div class="empty">No tasks or sections found.</div>';box.classList.remove("hidden")}
$("#globalSearch").oninput=e=>search(e.target.value);$("#globalSearch").onkeydown=e=>{if(e.key==="Escape"){$("#searchResults").classList.add("hidden");e.target.value=""}if(e.key==="Enter"){const first=$("#searchResults .search-hit");if(first)first.click()}};document.addEventListener("click",e=>{if(!e.target.closest(".search-box")&&!e.target.closest(".search-results"))$("#searchResults").classList.add("hidden")});

const storedSession=localStorage.getItem(SESSION_KEY);if(storedSession&&accounts[storedSession])openApp(storedSession);else setAuthMode("login");setInterval(checkReminders,30000);setInterval(()=>{if(user)renderReminders()},60000);
>>>>>>> e8f8cb887c8a9ae98b9c4951b6a60949a4a8e2d1
